### ISSUE TITLE
DHCP只能支持设置64个mac地址绑定ip，超过64个的不起作用

### ISSUE THREAD

**Issue by ulion** [hiboyhiboy/opt-script#116]
查了一下原因，问题在于trunk/user/rc/services_ex.c中 DHCPD_STATIC_MAX 限定在了64，导致UI上超过64个mac绑定ip之后的都不起作用没有被更新到dhcp-hosts.rc里。

所以希望发布下个版本的时候能增大这个限制，比如到128？望考虑！

**Comment by hiboyhiboy** [comment]
已修改128，请更新后测试修改

**Comment by ulion** [comment]
测试有效，已经可以支持到64个以上mac绑定ip了

**Comment by zhaojingliang** [comment]
trunk/user/rc/services_ex.c 文件在那里。

**Comment by ulion** [comment]
> trunk/user/rc/services_ex.c 文件在那里。

https://github.com/hanwckf/rt-n56u/blob/master/trunk/user/rc/services_ex.c
