### ISSUE TITLE
[建议]关于插件参数格式的修改

### ISSUE THREAD

**Issue by Love4Taylor** [hiboyhiboy/opt-script#12]
虽然不是必须 不过之前的方式实在不美观

1. 判断插件参数是否为空. 是, 则 "plugin":"", 反之 "plugin":"obfs-local", (作为客户端只会使用 local 所以不需要用户干涉)
2. 若插件参数不为空. 则 "plugin_opts":"obfs=http;obfs-host=www.bilibili.com" 反之 "plugin_opts":""

一个是这样做会美观很多 top 里 obfs-local 也不会带有参数, 第二则是官方的标准 json 格式
![](https://i.loli.net/2017/09/16/59bd3f3a80980.png)
![](https://i.loli.net/2017/09/16/59bd3e46d2ca0.png)
![](https://i.loli.net/2017/09/16/59bd3ddcd0c70.png)
![](https://i.loli.net/2017/09/16/59bd41d0ba509.png)

**Comment by hiboyhiboy** [comment]
下次再改
