### ISSUE TITLE
adguard home不要强制上游DNS

### ISSUE THREAD

**Issue by wsltshh** [hiboyhiboy/opt-script#138]
我的adguard home在AP模式的路由上，127根本没得用，能用也没意义，不如指向正确的dnsmasq地址。
以前还能在127下加一条正确的地址凑合用，现在直接完全强制了，这样对域名指定DNS也不行了，本来能用的功能现在都废了。
虽然dnsmasq什么的指定也可以，但是未必就把上游设置成dnsmasq什么的。
我想能否加个判断，只要配置文件里有127的条目就不要执行修改了，这样给127加个#标注掉就什么都不影响了#
前几天我试着是不强制了，这次更新后更强制了

**Comment by wsltshh** [comment]
无论如何，至少达到以前那样，不会影响上游DNS里的其它条目

**Comment by wsltshh** [comment]
看到今天只更新了Sh91_AdGuard_Home.sh，我还以为这么快就改变了呢😄

**Comment by wsltshh** [comment]
> > 看更新是修复了，关闭
> 
> 其实还是没修复，还是添加进去，影响相应的速度，自己改了代码，把命令做了

不知道，我更新完，卸载wget-ssl后没错误了

**Comment by wsltshh** [comment]
> > 看更新是修复了，关闭
> 
> 还是没，还是添加进去，影响相应的速度，自己改了修复代码，把命令做了

呃，以为是另一个问题呢，这个早修复了啊。
我的没问题，难道如我所说，需要保留127。加个# ？不可能吧.......

**Comment by 9dark9** [comment]
> > > 看更新是修复了，关闭
> > 
> > 
> > 还是没，还是添加进去，影响相应的速度，自己改了修复代码，把命令做了
> 
> 呃，以为是另一个问题呢，这个早修复了啊。 我的没问题，难道如我所说，需要保留127。加个# ？不可能吧.......
> 
> 我没去掉，加了# .........

下次更新版本我试试添加#，现在是改好了的
