### ISSUE TITLE
Feature request: IPv6 NAT

### ISSUE THREAD

**Issue by LGA1150** [hiboyhiboy/opt-script#16]
ISATAP/Teredo/Stateful DHCPv6 连接 IPv6 只能获取单个 IPv6 地址，要用 NAT 才可以让内网设备访问 IPv6
Padavan 的内核较低，不支持 ip6tables nat ，不过有第三方内核模块 NAPT66 https://github.com/mzweilin/napt66
由于编译此内核模块需要同时编译固件配套使用，我不想每一次更新都自己编译一次，想让你集成到固件中
参考：
http://www.jianshu.com/p/eb07eaac6167
http://www.jianshu.com/p/3a9ec169336e

**Comment by LGA1150** [comment]
没想到实现地如此迅速，经测试 NAPT66 确实可用，非常感谢。
不过目前有个小问题， insmod 后需要手动清除 ip6tables 防火墙规则，否则只能 ping 而 TCP 出不去
建议将 NAPT66 做成一个开关 `启用 IPv6 NAT`，并放在 `IPv6 内网设置` 中，如图所示
![image](https://user-images.githubusercontent.com/9155358/32698762-b306acee-c7e5-11e7-852d-8d6aec9cbc0b.png)
配合 [ISATAPD](https://github.com/shlusiak/isatapd) 就能实现 ISATAP IPv6 了，不如也加个 Tunnel ISATAP 的选项到 `IPv6 连接类型` 中？ Furthermore 考虑添加 IPv6 桥接（brctl 和 ebtables 在 WAN 和 LAN 间建立一个只允许 IPv6 通过的桥）以及 IPv6 中继（6relayd，华硕梅林固件的 `IPv6 Passthrough` 功能由此实现）

**Comment by chendaihang** [comment]
请问Padavan 如何实现teredo 我这没有外网ip 其他几种隧道都不能用

**Comment by hiboyhiboy** [comment]
2017-11-11:
新增模块 NAPT66【/lib/modules/$(uname -r)/kernel/net/napt66/napt66.ko】
