### ISSUE TITLE
H大能否把几个配置做到页面上，这样就不会因为更新固件全部重新配置

### ISSUE THREAD

**Issue by wztx** [hiboyhiboy/opt-script#6]
比如脚本下载地址的配置，不用每次更新固件了就去更改

frp的基本配置
[common]
server_addr = 
server_port = 
privilege_token =

[web]
privilege_mode = 
remote_port = 
type = 
local_ip = 
local_port = 
use_gzip = 
subdomain = 
custom_domains = 
host_header_rewrite =

**Comment by hiboyhiboy** [comment]
【说明】：现在从2017-10-22版本开始，更新固件只会自动重置/etc/storage/script、/etc/storage/www_sh里面的脚本，其他脚本不会自动重置，如果太旧版本刷新固件，有可能能出现脚本没更新，导致其功能出现问题，可手动重置路由内部储存达到强制更新脚本的效果。
【脚本】：如需手动更新，可自行查看脚本修改情况，手动重置。https://github.com/hiboyhiboy/opt-script

**Comment by superxp1412** [comment]
> 【说明】：现在从2017-10-22版本开始，更新固件只会自动重置/etc/storage/script、/etc/storage/www_sh里面的脚本，其他脚本不会自动重置，如果太旧版本刷新固件，有可能能出现脚本没更新，导致其功能出现问题，可手动重置路由内部储存达到强制更新脚本的效果。
> 【脚本】：如需手动更新，可自行查看脚本修改情况，手动重置。https://github.com/hiboyhiboy/opt-script

请问所谓的手动重置，具体是怎么操作的呢？需要自己下载脚本，放进/etc/storage/目录么？
