### ISSUE TITLE
ss订阅列表问题

### ISSUE THREAD

**Issue by kingwsi** [hiboyhiboy/opt-script#61]
window.atob解base64报错，订阅列表无法展示，我尝试处理了下(在chrome)，请问如何替换到固件里呢
```javascript
var _atob = global.atob ? function(a) {
        var res = ""
    	try{
    		res = global.atob(a);
    	} catch (e) {
    		res = a
    	}
        return res;
    } : function(a){
        return a.replace(/\S{1,4}/g, cb_decode);
    };
```

**Comment by hiboyhiboy** [comment]
```
mount --bind /opt/link_d.js /www/link_d.js
```
挂载方式能临时替换文件。
谢谢提供bug，估计是原生解码不支持特殊字符，现在改为直接用第三方解码

**Comment by kingwsi** [comment]
谢谢回复，我打印了下错误，发现是因为订阅节点的有些数据没有base64处理，但是解码的时候却用base64去解码的，报The string to be decoded is not correctly encoded，是不是可以在解码之前检查下呢

**Comment by kingwsi** [comment]
> 谢谢回复，我打印了下错误，发现是因为订阅节点的有些数据没有base64处理，但是解码的时候却用base64去解码的，报The string to be decoded is not correctly encoded，是不是可以在解码之前检查下呢

刚刚更新了固件 问题已解决

**Comment by cnboy95** [comment]
我就想要一份三月份固件，不知道能不能讨一份

**Comment by kingwsi** [comment]
> 我就想要一份三月份固件，不知道能不能讨一份

固件发布地址 https://t.me/s/pdcn1
