### ISSUE TITLE
建议增加使用 socks5、http、redir 代理功能

### ISSUE THREAD

**Issue by yjmp14** [hiboyhiboy/opt-script#83]
因路由器性能限制，直接在路由器上运行 SS、SSR、V2Ray 等代理时速度并不理想，故建议增加使用 socks5、http 、redir 代理功能。
具体为：在局域网其他性能更好的设备上运行 SS、SSR、V2Ray 等客户端，并允许局域网访问 socks5 或 redir 代理，路由器使用此 socks5 或 redir 代理，并通过 ss_tproxy 分流，实现路由器翻墙功能。

**Comment by yjmp14** [comment]
可以考虑内置 [https://github.com/hiboyhiboy/opt-script/issues/62#issuecomment-601687125](url) 提及的 [glider](https://github.com/nadoo/glider)。

**Comment by yjmp14** [comment]
> 可以考虑内置 [https://github.com/hiboyhiboy/opt-script/issues/62#issuecomment-601687125](url) 提及的 [glider](https://github.com/nadoo/glider)。

`./glider -verbose -listen redir://:1090 -forward socks5://192.168.123.2:1080`
经测试在路由器上运行 glider 可以实现所需功能，请 h 大考虑将其内置到 opt 中。

**Comment by xfl12345** [comment]
不是有ss_tproxy就可以redirect所有透明代理的流量吗？固件里，V2RAY和SS都有自动脚本支持跑ss_tproxy的。（虽然V2RAY的自动脚本跑ss_tproxy有问题，我已经pull request了，你可以照着修改一下）如果想纯粹redirect内网流量到指定socks5代理服务器，也有transocks和ip2socks可以选择，不太明白你的需求。

**Comment by yjmp14** [comment]
> 不是有ss_tproxy就可以redirect所有透明代理的流量吗？固件里，V2RAY和SS都有自动脚本支持跑ss_tproxy的。（虽然V2RAY的自动脚本跑ss_tproxy有问题，我已经pull request了，你可以照着修改一下）如果想纯粹redirect内网流量到指定socks5代理服务器，也有transocks和ip2socks可以选择，不太明白你的需求。

抱歉，因为在“广告屏蔽”模块里，刚看到有 transocks 和 ip2socks，但我试了下没有成功，不知道需要如何配置？

**Comment by xfl12345** [comment]
> > 不是有ss_tproxy就可以redirect所有透明代理的流量吗？固件里，V2RAY和SS都有自动脚本支持跑ss_tproxy的。（虽然V2RAY的自动脚本跑ss_tproxy有问题，我已经pull request了，你可以照着修改一下）如果想纯粹redirect内网流量到指定socks5代理服务器，也有transocks和ip2socks可以选择，不太明白你的需求。
> 
> 抱歉，因为在“广告屏蔽”模块里，刚看到有 transocks 和 ip2socks，但我试了下没有成功，不知道需要如何配置？

兄弟，我也没成功，但网上有人就是用过这两个，还写了教程，我试了无效，也没有深入探索到底哪里出了问题，你姑且使用ss_tproxy吧。不巧的是，ss_tproxy也有BUG，不过被我修复了，你可以自己手动编辑脚本文件试试。别忘记到“恢复设置”菜单里保存/etc/storage以烧写到Flash里。
https://github.com/hiboyhiboy/opt-script/pull/82/files

**Comment by xfl12345** [comment]
> > 不是有ss_tproxy就可以redirect所有透明代理的流量吗？固件里，V2RAY和SS都有自动脚本支持跑ss_tproxy的。（虽然V2RAY的自动脚本跑ss_tproxy有问题，我已经pull request了，你可以照着修改一下）如果想纯粹redirect内网流量到指定socks5代理服务器，也有transocks和ip2socks可以选择，不太明白你的需求。
> 
> 抱歉，因为在“广告屏蔽”模块里，刚看到有 transocks 和 ip2socks，但我试了下没有成功，不知道需要如何配置？

这么晚了还不睡？难道你也是夜猫子程序员？

**Comment by yjmp14** [comment]
> > > 不是有ss_tproxy就可以redirect所有透明代理的流量吗？固件里，V2RAY和SS都有自动脚本支持跑ss_tproxy的。（虽然V2RAY的自动脚本跑ss_tproxy有问题，我已经pull request了，你可以照着修改一下）如果想纯粹redirect内网流量到指定socks5代理服务器，也有transocks和ip2socks可以选择，不太明白你的需求。
> > 
> > 
> > 抱歉，因为在“广告屏蔽”模块里，刚看到有 transocks 和 ip2socks，但我试了下没有成功，不知道需要如何配置？
> 
> 兄弟，我也没成功，但网上有人就是用过这两个，还写了教程，我试了无效，也没有深入探索到底哪里出了问题，你姑且使用ss_tproxy吧。不巧的是，ss_tproxy也有BUG，不过被我修复了，你可以自己手动编辑脚本文件试试。别忘记到“恢复设置”菜单里保存/etc/storage以烧写到Flash里。
> https://github.com/hiboyhiboy/opt-script/pull/82/files

transocks 和 ip2socks 自动配置的 ss_tproxy 有问题，似乎是强制开启重定向 DNS 导致的。新开一个 issue 了。
