### ISSUE TITLE
clash 报错。

### ISSUE THREAD

**Issue by rootphantomer** [hiboyhiboy/opt-script#99]
【下载】: 下载【/opt/app/clash/clash_webs.tgz】错误，2次下载md5不匹配！【https://opt.cn2qq.com/opt-file/clash_webs.tgz】
May 31 21:24:08 【下载】: 删除【/opt/app/clash/clash_webs.tgz】文件，麻烦看看哪里问题！

**Comment by rootphantomer** [comment]
May 31 21:24:02 【下载】: 下载失败:【/tmp/checkmd5/10692】 URL:【https://opt.cn2qq.com/opt-file/clash_webs.tgz】
May 31 21:24:02 【下载】: 重新下载:【/tmp/checkmd5/10692】 URL:【https://raw.githubusercontent.com/hiboyhiboy/opt-file/master/clash_webs.tgz】
May 31 21:24:08 【下载】: 下载失败:【/tmp/checkmd5/10692】 URL:【https://raw.githubusercontent.com/hiboyhiboy/opt-file/master/clash_webs.tgz】
May 31 21:24:08 【下载】: wget_err ：404错误！
May 31 21:24:08 【下载】: 下载【/opt/app/clash/clash_webs.tgz】错误，2次下载md5不匹配！【https://opt.cn2qq.com/opt-file/clash_webs.tgz】
May 31 21:24:08 【下载】: 删除【/opt/app/clash/clash_webs.tgz】文件，麻烦看看哪里问题！

**Comment by gaoshijun1993** [comment]
遇到同样问题,手动下载这个文件又是可以的

**Comment by gaoshijun1993** [comment]
可以手动下载:
wget -O /opt/app/clash/clash_webs.tgz https://raw.githubusercontent.com/hiboyhiboy/opt-file/master/clash_webs.tgz
tar -xzvf /opt/app/clash/clash_webs.tgz -C /opt/app/clash ; cd /opt
rm -f /opt/app/clash/clash_webs.tgz

然后在web控制台重启clash就可以了

**Comment by rootphantomer** [comment]
@gaoshijun1993 具体是在路由器哪个功能点可以执行这个shell命令？

**Comment by gaoshijun1993** [comment]
ssh到路由器执行即可

**Comment by rootphantomer** [comment]
@gaoshijun1993 好的。
